#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}

branches:
  only:
    - master
    - develop

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# clone directory
clone_folder: C:\projects\ChocolateyGUI

# environment variables
environment:
  MyGetDevelopApiKey:
    secure: LeTveN6ryggcXR4fgZcaMOdvVHFxR6NNZZpaaxCG83D8waN4D1eEoLRv+5ZvLKLF
  MyGetDevelopFeedUrl: https://www.myget.org/F/chocolateygui
  MyGetMasterApiKey:
    secure: zTAGaSiQMYJeCl1dD+i/e0ZOZMT9Hq3nXd9fCzZE8/rHRnOkj4uUETfA2VbgjpCV
  MyGetMasterFeedUrl: https://www.myget.org/F/chocolateygui_master/
  ChocolateyApiKey:
    secure: 2Sbie8uhFjl1v+NtLuR1oGcWnQE2M87jq0fSEwFOYcnNEC5qdwCkgVOG0MmC2Ffv
  ChocolateyFeedUrl: https://chocolatey.org/
  GitHubUserName:
    secure: 9zbEIVfl69s/qhei6qkdeA==
  GitHubPassword:
    secure: XSuLygmr83zEpWcXIXMXGocN0QbooLud1eIMA3mQWKkT9LAU4TyrijLBcJIo7bD7
   
#---------------------------------#
#       build configuration       #
#---------------------------------#

build_script:
  - ps: .\BuildScripts\build.ps1
  
test: off

#---------------------------------#
#      caching configuration      #
#---------------------------------#

cache:
  - Source\packages

#---------------------------------#
#  notifications configuration    #
#---------------------------------#
notifications:
  - provider: Webhook
    url: https://webhooks.gitter.im/e/4933c447ea42a0480587
    on_build_success: true
    on_build_failure: true
    on_build_status_changed: true
