#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 1.0.{build}

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# clone directory
clone_folder: C:\projects\ChocolateyGUI

# environment variables
environment:
  MyGetApiKey:
    secure: LeTveN6ryggcXR4fgZcaMOdvVHFxR6NNZZpaaxCG83D8waN4D1eEoLRv+5ZvLKLF
  MyGetFeedUrl: https://www.myget.org/F/chocolateygui
  ChocolateyApiKey:
    secure: 2Sbie8uhFjl1v+NtLuR1oGcWnQE2M87jq0fSEwFOYcnNEC5qdwCkgVOG0MmC2Ffv
  ChocolateyFeedUrl: http://chocolatey.org/api/v2/
   
#---------------------------------#
#       build configuration       #
#---------------------------------#

build_script:
  - cmd: build.bat PackageSolution
  
after_build:
  - ps: Write-Host "Uploading StyleCop results for build."
  - ps: $wc = New-Object 'System.Net.WebClient'
  - ps: $wc.UploadFile("https://ci.appveyor.com/api/testresults/stylecop/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\BuildArtifacts\StyleCopReport.xml))

test: off

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: BuildArtifacts\ChocolateyGUI.msi
    name: ChocolateyGUI Installer

  - path: BuildArtifacts\ChocolateyGUI.*.nupkg
    name: ChocolateyGUI Chocolatey Package	

#---------------------------------#
#      caching configuration      #
#---------------------------------#

cache:
  - Source\packages